### ISSUE TITLE
Not working with React Native

### ISSUE THREAD

**Issue by shahankit** [stefalda/react-localization#1]
```
let strings = new LocalizedStrings({
  en:{
    how:"How do you want your egg today?",
    boiledEgg:"Boiled egg",
    softBoiledEgg:"Soft-boiled egg",
    choice:"How to choose the egg"
  },
  it: {
    how:"Come vuoi il tuo uovo oggi?",
    boiledEgg:"Uovo sodo",
    softBoiledEgg:"Uovo alla coque",
    choice:"Come scegliere l'uovo"
  }
});
```
This line gives error cannot read property indexOf of undefined.

**Comment by shahankit** [comment]
I think this is because [this](https://github.com/stefalda/react-localization/blob/master/lib/LocalizedStrings.js#L45). For react native `navigator.language || navigator.interfaceLanguage` would return undefined.

**Comment by shahankit** [comment]
https://github.com/stefalda/react-localization/pull/2

**Comment by stefalda** [comment]
Hi @shahankit, with react-native you should use ReactNativeLocalization [https://github.com/stefalda/ReactNativeLocalization](ReactNativeLocalization )

This is a simple port from that version, but it's not intended to be used instead of that one...

**Comment by shahankit** [comment]
I first decided to use that only but it requires changing native side, rather using this is javascript side change so localization feature can be updated on the air.
