### ISSUE TITLE
Hyphenated language codes

### ISSUE THREAD

**Issue by MatthewPorter31** [stefalda/react-localization#104]
I'm looking for some more control in the strings object based on a user's country. Is it possible to format the input object with country codes?

For example, `pt` vs `pt-BR`:
```
export const data = {
  ptBr: {
    reception: 'recepção'
  },
  pt: {
    reception: 'receção'
}
```

**Comment by stefalda** [comment]
Hi, yes it's supported.
The format should be pt-BR (but check what the library returns as current format).

**Comment by MatthewPorter31** [comment]
Thanks, will check it out.
