### ISSUE TITLE
Localize a dynamically created text

### ISSUE THREAD

**Issue by piyaa** [stefalda/react-localization#11]
I have many strings that would be defined by the user(i.e. dynamically created) and not hard coded, so cannot be stored as json. Not sure I see a way  to localize those kind of strings with this approach? Any ideas?

**Comment by stefalda** [comment]
Hi,
 I think the easiest solution would be to reinstantiate the LolalizedStrings object by passing an updated json as constructor...

**Comment by piyaa** [comment]
so does it always has to be an object that would be passed to LocalizedStrings, can we pass a simple text to it?
```
<App
 state="somestate"
  language= "en"
   states={[
        {
        //some fields
        },
      ]}
 activeState="yes"
url="https://google.com"
 <div>some content here</div>
 </App>
```

in the render funtion:
```
render()
 {
return (
<div>
<MyComp url={this.props.url}/>
        <OtherComp/>
          <OtherComp2 modules={this.props.modules} active={this.props.activeState} 
          {this.renderRoutes()}
          <OtherComp3 user={this.props.user}/>
          <div>
            <Icon /> //1st icon
            <span />
            <Icon}/>2nd icon
          </div>
</div>
 `<div>{this.props.children}</div>`
```

This will render the entire application, now how i localize this content i.e `this.props.children`?
