### ISSUE TITLE
Incorrect TypeScript Definition

### ISSUE THREAD

**Issue by MasterEric** [stefalda/react-localization#113]
This library has the following TypeScript definition:

https://github.com/stefalda/react-localization/blob/master/lib/LocalizedStrings.d.ts#L58

However, this definition is missing the `options` parameter, as seen here (from the `localized-strings` library this extends):

https://github.com/stefalda/localized-strings/blob/master/lib/LocalizedStrings.d.ts#L76

The issue was mentioned in #101 but was dismissed by a user who did not understand how this library works.

**Comment by stefalda** [comment]
You're right!

Can you create the PR, or I'll do it myself asap...
Thank you

**Comment by MasterEric** [comment]
> You're right!
> 
> Can you create the PR, or I'll do it myself asap...
> Thank you

@stefalda Done. #114

**Comment by stefalda** [comment]
Merged and published new version.
Thank you
