### ISSUE TITLE
Not working with recent versions of react

### ISSUE THREAD

**Issue by AdrianaAC** [stefalda/react-localization#116]
Hi! 

When installing react-localization, i get an error:

npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^15.6.0" from react-localization@1.0.16

Is this issue been reported by other users? I couldn't find any issue regarding this subject, neither a way to proper install react-localization.

**Comment by AdrianaAC** [comment]
I'll try to revert react to its previous version and try again using react-localization.
Tried npm and yarn neither one of them worked, also tried to install a previous version of react-localization, but it also gave me the same error.

**Comment by stefalda** [comment]
I've tried with npm 6.14.10 and React 17 getting just the warning...

I believe that npm 7 tries to download peer dependencies... but I'm not sure...

Let me know.

**Comment by AbdelhayA0100** [comment]
same error with me 
node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^15.6.0" from react-localization@1.0.16
npm ERR! node_modules/react-localization
npm ERR!   react-localization@"*" from the root project
npm ERR!

**Comment by MasterEric** [comment]
I can confirm this issue likely has to do with [peer dependencies now being installed automatically](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies).

The long-term solution is to merge #120 and build a new bugfix release, but in the meantime you can call `npm install --legacy-peer-deps` to restore the old behavior.

**Comment by AbdelhayA0100** [comment]
Where should you install an old version
npm i react-localization@1.0.10

**Comment by stefalda** [comment]
Released a new versione
