### ISSUE TITLE
installing react-localization

### ISSUE THREAD

**Issue by AbdelhayA0100** [stefalda/react-localization#119]
When installing react-localization, i get an error:
npm --v 7.9.0
node_modules/react
npm ERR! react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^15.6.0" from react-localization@1.0.16
npm ERR! node_modules/react-localization
npm ERR! react-localization@"*" from the root project
npm ERR!

**Comment by stefalda** [comment]
It should be fixed with latest update.
