### ISSUE TITLE
Still get the error, interfaceLanguage undefined

### ISSUE THREAD

**Issue by piyaa** [stefalda/react-localization#12]
I still get this error:
`LocalizedStrings.js:91 Uncaught ReferenceError: interfaceLanguage is not defined(…)`.I see that an issue was opened for it, is it resolved?, for some reason i still see the issue. I'm i missing something?

**Comment by stefalda** [comment]
Have you tested with latest version? 0.8...
I guess there some problem with getting current language from the browser...
