### ISSUE TITLE
Language urls

### ISSUE THREAD

**Issue by virik** [stefalda/react-localization#125]
Hi,

For SEO and UX purposes, it would be great having custom urls for additional languages: sitename.com for default language and sitename.com/en, sitename.com/no, for other languages.

Would this be possible somehow?

**Comment by stefalda** [comment]
Hi,
 I guess it's feasable but I don't believe it should be done by this library, I see it more like a routing matter...

You could intercept the document.url and change the language accordingly.

Stefano
