### ISSUE TITLE
Clean localization file by removing the unused keys

### ISSUE THREAD

**Issue by HoussemDjeghri** [stefalda/react-localization#126]
Hi, in our prod app we have two localization files **en** and **fr** that have both **1192** keys in them that accumulated after two years of updating the localization, so we end up with a lot of unused keys the files, so we want to know if there is a way to clean the localization files by removing the unused keys without passing throw the **1192** keys ?

**Comment by stefalda** [comment]
Hi, unfortunately there's no automatic way to detect unused keys...
Sorry
