### ISSUE TITLE
How does the formatString work?

### ISSUE THREAD

**Issue by piyaa** [stefalda/react-localization#13]
Not an issue, but need more clarification on an api.
I tried running an example using the formatString() and resulted:
`tests are {0} configurable to your liking.Select from all tests {1}, to customize your own.`

here is the json:

```
{
    "title": "title.",
    "test": "Start your first test",
    "description": "tests are {0} configurable to your liking.Select from all tests {1}, to customize your own."
}
```

what im doing wrong?

**Comment by stefalda** [comment]
How did you call it?

It should be something like:

`strings.formatString(strings.description, "THIS GOES IN 0", "THIS GOES IN 1");
`

I hope this helps..

Stefano

**Comment by hakimCZE** [comment]
According to documentation, we could use react components.
```javascript
// React components can be used as placeholder values! Useful when using links or customizing style
strings.formatString(strings.onlyForMembers, <a href="http://login.com">{strings.login}</a>)
strings.formatString(strings.iAmText, <b>{strings.bold}</b>)
```
But this results in printing [Object Object]
