### ISSUE TITLE
 npm package release (1.0.19) has no matching tag in this repo

### ISSUE THREAD

**Issue by dvd95** [stefalda/react-localization#138]
The version 1.0.19 of react-localization is published but I am unable to find a Tag for this Repo.

Is there any reason why it is not tagged yet?

**Comment by dvd95** [comment]
@stefalda, can you please mention the reason so that we can decide on the usage.

**Comment by stefalda** [comment]
Sorry, i've forgotten to push the tag... I've done it today, now it should be ok.

Thanks
