### ISSUE TITLE
Default Value if no language is found?

### ISSUE THREAD

**Issue by newfylox** [stefalda/react-localization#15]
I have an english and french website. I would like first detected value to be used if 'english' is not found
```javascript
let strings = new LocalizedStrings({
  en: {
    signinTitle: 'Sign in',
  },
  fr: {
    signinTitle: 'Connexion',
    signoutTitle: 'Déconnexion', // <-- use this value if 'signoutTitle' is not defined in english
  }
});
```
It could also be to add a 'default' key
```javascript
let strings = new LocalizedStrings({
  default: {
    signoutTitle: 'test' // <-- English is my default language browser but not defined in 'en', so use the 'default' key value
  }
  en: {
    signinTitle: 'Sign in',
  },
  fr: {
    signinTitle: 'Connexion',
    signoutTitle: 'Déconnexion',
  }
});
```

**Comment by stefalda** [comment]
Hi, the default language should be the FIRST language set so in your case it would be english... 
is it what you desire?

**Comment by newfylox** [comment]
Well, actually there's a strange bug.

For example, if I have this

```javascript
let strings = new LocalizedStrings({
  fr: {
    signinTitle: 'Connexion',
    test: 'test', // <-- Should be the default value when key 'test' is used because 'fr' is the first one
  },
  en: {
    signinTitle: 'Sign In',
  }
});
```

and if my browser is set like this (Let's suppose I'm english)

- ![01](https://cloud.githubusercontent.com/assets/3361669/20369549/96d78938-ac27-11e6-8c48-d062686eb661.png)

I got this

- ![02](https://cloud.githubusercontent.com/assets/3361669/20369558/af2d5544-ac27-11e6-86c1-56cf5db76184.png)

But if I'm another language (Italian)

- ![03](https://cloud.githubusercontent.com/assets/3361669/20369570/c00cac8e-ac27-11e6-8ebc-a0603ebb2f06.png)

Now it works

- ![04](https://cloud.githubusercontent.com/assets/3361669/20369574/c5cdd508-ac27-11e6-9643-eae2fdbd5db6.png)

It seems like the default choice (first declared language) will work only if we use a language not defined, otherwise it will output 'empty' string (maybe I'm wrong too)

**Comment by DCKT** [comment]
Hi,

What about doing like other plugins and print the key ? This is more helpful for debugging

**Comment by stefalda** [comment]
@DCKT I've fixed the problem and now using getInterfaceLanguage() works so you can decide to print it or not...

**Comment by newfylox** [comment]
Thanks guys!
