### ISSUE TITLE
Setting reserved words like "language" doesn't throw any warnings.

### ISSUE THREAD

**Issue by mimshwright** [stefalda/react-localization#25]
If you define a word for "language", the getLanguage() function will return the localized string for the key "language". Presumably this would happen if you used a key called "getLanguage" or any other internal name as well.

Expected:
It should warn you whenever you try to define a reserved word.

**Comment by stefalda** [comment]
I've merged your PR with the property validation and renamed all the internal variables prefixing them with _.
