### ISSUE TITLE
In v0.0.16, setContent throws reserved keyword error when trying to replace content of existing keypaths

### ISSUE THREAD

**Issue by kieferaguilar** [stefalda/react-localization#29]
For purposes of testing React components that use strings from react-localization, I would like to be able set the content of `LocalizedStrings` instance with strings identifying each key's language-independent keypath. For example, suppose I have:

```
var strings = new LocalizedStrings({
 en: {
   a: {
     b: { x: "foo", y: "bar" },
     c: { z: "baz" }
    }
 }
});
```

I would like to be able to set the content of `strings` with:

```
const contentForTesting = {
 en: {
   a: {
     b: { x: "a.b.x", y: "a.b.y" },
     c: { z: "a.c.z" }
    }
 }
};
```

In `react-localization v0.0.15`, I could accomplish this as follows:

```
strings.props = contentForTesting;
strings.setLanguage(strings.getLanguage()); // Resets LocalizedStrings object with new props
```

In `react-localization v0.0.16`, this no longer works with the introduction of `setContent()`.

**Expected behavior:**

`strings.setContent(contentForTesting)` maintains `en` as current language and successfully replaces the content of `strings`.

**Observed behavior:** 

`strings.setContent(contentForTesting)` throws an error because `"a"` is a reserved keyword.

**Comment by fbacker** [comment]
Same problem here. Want to overwrite existing texts.

Remove from **'setContent'** will do the trick

    //this._validateProps(props[this._defaultLanguage]);

**Comment by stefalda** [comment]
The validation has been added to prevent the library from breaking... anyway I need to make some tests to understand why "a" is considered an original object property instead of an added one...

**Comment by stefalda** [comment]
I've modified the way reserved property names are checked and added a test for this... now it works (0.17)

**Comment by kieferaguilar** [comment]
@stefalda I am seeing the same issue in v0.0.17. It would appear that you've fixed the issue in `src/LocalizedStrings.js` but not in `lib/LocalizedStrings.js`. Hence, the specs pass but the issue persists.

One other small thing: It would be nice if `props` could be "re-exposed"  (or a method `getProps()`, if you don't want to expose it directly). v0.0.17 had "unexposed" it by the naming convention `_props`. Why this request? For purposes of testing components, I compute the contents of `contentForTesting` from `strings.props` rather than explicitly write out those keypaths as I did to demonstrate the bug.

Thank you for your attention and for having quickly addressed this bug report!
