### ISSUE TITLE
works only if remote debugger is running

### ISSUE THREAD

**Issue by tothzsofia** [stefalda/react-localization#33]
I got this error when tried to run it without the remote debugger.
Help me please!

![nevtelen2](https://user-images.githubusercontent.com/26714395/27831689-1163ef4e-60cc-11e7-92d9-51f08bb650f4.png)

**Comment by stefalda** [comment]
Hi, you should use the react-native-localization package instead of the react-localization one...

**Comment by tothzsofia** [comment]
Okay. Thanx ;)

**Comment by henrikra** [comment]
@stefalda This can be closed?

**Comment by stefalda** [comment]
Sure...
