### ISSUE TITLE
Have anyone tried this module from expressjs backend ?

### ISSUE THREAD

**Issue by asotog** [stefalda/react-localization#34]
I'm trying to use the same strings in the backend as well to render some stuff in the page markup, like prerender the `<title></title>` tag before react app is loaded

**Comment by stefalda** [comment]
I think the main problem would be detecting the default language to use, because it access the Navigator object to identify it...

**Comment by asotog** [comment]
I see, will close this, just wanted to know if was checked there too, thanks
