### ISSUE TITLE
[BUG] Wrong language is chosen on Chrome

### ISSUE THREAD

**Issue by henrikra** [stefalda/react-localization#36]
## Problem description
Chrome version: 59.0.3071.115
When I have selected other language than English for example Finnish because I am from Finland after all :D
It still choose English as my language inside of `_getInterfaceLanguage` despite my language was set to Finnish.

I debugged `_getInterfaceLanguage` and the logic always goes to first branch of the if statement which chooses language from `navigator.languages[0]`
But as you can see from this image the finnish language is last item in the array
![image](https://user-images.githubusercontent.com/12229968/28077958-e7c40610-666b-11e7-8ac3-cbfdb116479e.png)

## Possible solution
I think possible solution would be to move second if statement branch as first so it would first check if `navigator.language` would exist and use that. After that it would use `navigator.languages[0]`

Also according to this all browsers should have `navigator.language` so it should be priority
![image](https://user-images.githubusercontent.com/12229968/28107733-b3e5348c-66f1-11e7-99ac-ef16cf9269de.png)
Source: [detect-browser-language-in-javascript](https://zzz.buzz/2016/01/13/detect-browser-language-in-javascript/)

**Comment by stefalda** [comment]
it seems fair enough to use navigator.language first...

**Comment by henrikra** [comment]
@stefalda Fix PR here https://github.com/stefalda/react-localization/pull/38
