### ISSUE TITLE
Define strings in a separate file

### ISSUE THREAD

**Issue by srajchevski** [stefalda/react-localization#4]
Not an issue, just need help with something. I'm having trouble with putting the strings object in a separate file (because i will have lots and lots of text), and import it in the components i need it.

How would the process of changing languages go then? Any help? 
Thanks. :)

**Comment by alesten** [comment]
I've done it like this.

I have a commen file looking like this:
```
import LocalizedStrings from 'react-localization';

import da from './da';
import en from './en';
import de from './de';

export default new LocalizedStrings({
    da,
    en,
    de
});
```
Then each lang is in separate files and just loaded in.
When I then want to use the string I do:

```
import localization from '../../localization';

class Navbar extends React.Component{
    render(){
        return (
            <div className="App">
                <div className="App-header">
                    <h2>{localization.myString}</h2>
                </div>
            </div>
        );
    }
}
```

I hope you can use this :)

**Comment by piyaa** [comment]
what is ../../localization file? I dont see it in the source code.Also what is the "myString" defined as?

**Comment by alesten** [comment]
The ../../localization file the commen file in the first code example. 

"myString" is the variable name for the translatable string.

**Comment by piyaa** [comment]
Thanks gotcha!! how about if I want to translate the entire object, i.e I have something like this:
`import LocalizedStrings from 'react-localization';`
`  import en from './languages/en.json';`
`import jp from './languages/jp.json';`

`    let strings = new LocalizedStrings({en,jp});` //return an object containing:

json:
```
{
  "obj": {
    "save": "Save Button"
  },
  "obj2": {
    "search": "Search...",
    "showStock": "Only show products in stock"
  },
  "obj3": {
    "name": "Name",
    "price": "Price"
  }
}
```
how about if I want to translate the entire object, does the lib support it? Thanks!

**Comment by alesten** [comment]
I don't know if that's supported. I'm not the creator. But give it a try "strings.obj.save" and let me know if it works

**Comment by piyaa** [comment]
Ooops sorry, didn't notice that, well I tried and it doesn't work for me, it just displays the english text always, if even I translate to other lang, may be it needs a way to identify the lang change that user makes. With the inline json ( as mentioned in the ReadMe example), it works, but when i seperate the files, Any ideas??

**Comment by alesten** [comment]
Did you set the language you want to display so it doesn't default to English?

**Comment by piyaa** [comment]
ahh, actually I wasnt using the correct lang code, it works for the obj as well! Thanks @alesten for your help!

**Comment by alesten** [comment]
You are very welcome!
