### ISSUE TITLE
formatString - Replacing string with a JSX element return [object Object]

### ISSUE THREAD

**Issue by JohnnyChedid** [stefalda/react-localization#41]
```
let strings = new LocalizedStrings({
  en:{
      dashboard    : "{0} dashboard",
  }
})
```
Now using the formatString function and passing to it a JSX element returns [object Object]

`strings.formatString(strings.dashboard, <b>Johnny</b>)}`

The above line is returning the string

> [object Object] dashboard

While the expected result should be

> **Johnny** dashboard

**Comment by JohnnyChedid** [comment]
Sorry, I had an older version.

**Comment by lusineartenyan** [comment]
But with the last version is the same issue

**Comment by mehmetkose** [comment]
"test string in list [object Object]"
