### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by acierto** [stefalda/react-localization#43]
![screen shot 2017-08-03 at 15 09 08](https://user-images.githubusercontent.com/2265094/28923270-c2154b14-785d-11e7-85ce-1305e966cc2f.png)

**Comment by filtersweep** [comment]
Just stumbled across this myself. Some context: 

https://stackoverflow.com/questions/31119300/ie11-object-doesnt-support-property-or-method-includes-javascript-window

Thankfully, I've been able to work around it by adding babel-polyfill to my webpack build:

https://babeljs.io/docs/usage/polyfill/

**Comment by henrikra** [comment]
@filtersweep Can you do PR that uses https://babeljs.io/docs/usage/polyfill/ and add that polyfill as plugin to `.babelrc`. I think that should work :)

**Comment by acierto** [comment]
The workaround is clear, but I expect that library itself to be transpiled to the code where I don't need to add myself any polyfills. But the current solution adds extra configuration for the usage of this lib. We are using in current project more than 40 java libs, and this single one only requires to add an polyfill.

**Comment by acierto** [comment]
https://github.com/stefalda/react-localization/pull/44/

**Comment by stefalda** [comment]
Hi,
 I've fixed the issue in version 0.1.2.

**Comment by acierto** [comment]
Hi, thank you!
