### ISSUE TITLE
import strings to anther class

### ISSUE THREAD

**Issue by shayja** [stefalda/react-localization#49]
I created a language strings file e.g.:

import LocalizedStrings from 'react-localization';
 
let strings = new LocalizedStrings({
 en:{
   how:"How do you want your egg today?",
 },
 it: {
   how:"Come vuoi il tuo uovo oggi?"
 }
});

The API works OK if I use the same file
strings.setLanguage('en');
console.log(strings.how);

When I call the API from another file the strings object is empty ({}) and strings.how will return undefined:

import React from 'react';

//the import line:
**import strings from '../common/LocalizedStrings';**

export default class MyPageNameHere extends React.Component{
	constructor (props) {
	super(props);
	
	**console.log(strings);
	console.log(strings.how);**
  }
}

Hope anyone can help.

**Comment by stefalda** [comment]
Do you export the string variable?

**Comment by shayja** [comment]
Thanks stefalda, this line solved my problem:
export default strings;
