### ISSUE TITLE
Not checking for undefined in interfaceLanguage

### ISSUE THREAD

**Issue by anzzstuff** [stefalda/react-localization#5]
I was wondering why my application wouldn't work on my android phone's built in browser, and found out here's the problem. You are checking for languages with this:

`let interfaceLanguage = navigator.languages ? navigator.languages[0] : (navigator.language || navigator.userLanguage || 'en-US');`

If it finds an "undefined" value, it will return it, which will cause the following error in _getBestMatchingLanguage:

> Uncaught TypeError: Cannot read property 'indexOf' of undefined

Replacing the line with this fixes the issue:

`    let interfaceLanguage = (navigator.languages && typeof navigator.languages !== 'undefined' && navigator.languages[0] && typeof navigator.languages[0] !== 'undefined') ? navigator.languages[0] : 
            ((navigator.language && typeof navigator.language !== 'undefined') ? navigator.language : 
            ((navigator.userLanguage && typeof navigator.userLanguage !== 'undefined') ? navigator.userLanguage :
            'en-US')); 
`

**Comment by stefalda** [comment]
If you create a pull request I'll merge it...

**Comment by victorbello** [comment]
@stefalda, when will you update the node package? I just downloaded the library and the new code that fixes the issue is not there.

**Comment by stefalda** [comment]
Sorry, I'm away from my pc so I cannot commit to npm. In the meantime you can specify git as source to get the most updated version. As soon as I'm back home I'll commit the version to npm.

**Comment by stefalda** [comment]
I've finally updated the node package.
Sorry for the delay.
