### ISSUE TITLE
Use with TypeScript

### ISSUE THREAD

**Issue by ambujs** [stefalda/react-localization#51]
Hello, I'm trying to use this in a TypeScript file but getting this error:
`Uncaught TypeError: LocalizedStrings is not a constructor`

Here's what my TypeScript file looks like:
`import * as LocalizedStrings from "react-localization";`
.
.
.
`export class EditResponse extends React.Component<{}, IEditResponseState> {
    constructor(props: any) {
        super(props);`

`        let strings = new LocalizedStrings({
            en: {
                how: "How do you want your egg today?",
                boiledEgg: "Boiled egg",
                softBoiledEgg: "Soft-boiled egg",
                choice: "How to choose the egg"
            },
            it: {
                how: "Come vuoi il tuo uovo oggi?",
                boiledEgg: "Uovo sodo",
                softBoiledEgg: "Uovo alla coque",
                choice: "Come scegliere l'uovo"
            }
        });`

Please help!

**Comment by stefalda** [comment]
Hi, 
I've reviewed the definition file and now it seems to work... just update to version 0.13
