### ISSUE TITLE
formatString not working with falsy values as parameter

### ISSUE THREAD

**Issue by legrak** [stefalda/react-localization#62]
S.formatString("Value should be between {0} and {1}", 0, 10).

```
var valueForPlaceholder = valuesForPlaceholders[matchedKey];
```
here valueForPlaceholder is resolved just fine.

```
if (!valueForPlaceholder) {
   valueForPlaceholder = valuesForPlaceholders[0][matchedKey];
}
```
here (because of 'if (!0)' is true) it goes undefined.

```
if (isReactComponent(valueForPlaceholder)) {
```
here it crashes

**Comment by TryingToImprove** [comment]
I got the same error.

I resolved it with adding `.toString`.


```js
strings.formatString(strings.myString, 0.toString())
````

**Comment by joshsalverda** [comment]
This was my fault, I have another PR incoming shortly... You'd think this is my first time writing JS 😩
