### ISSUE TITLE
Typescript export LocalizedStrings

### ISSUE THREAD

**Issue by Larsrdev** [stefalda/react-localization#68]
Hey, 
I am new to Typescript, but having problems using the code from the second comment: [Issue 42](https://github.com/stefalda/react-localization/issues/42)

There is some error in LocalizedStrings.d.ts:
`export type LocalizedStrings<T> = LocalizedStringsMethods & T;
  
    interface LocalizedStringsFactory {
        new <T>(props: GlobalStrings<T>): LocalizedStrings<T>;
    }
  
    var LocalizedStrings**Factory**: LocalizedStringsFactory;
    export default LocalizedStrings**Factory**;`

The LocalizedStrings should be renamed to LocalizedStrings**Factory**, otherwise we cannot use both (type and var) at the same time. 

My own code:
`
// strings.ts

import { enStrings } from "./en";
import { deStrings } from "./de";
import LocalizedStringsFactory, {LocalizedStrings} from "react-localization";

export interface LocaleStrings {
    key1: string;
    key2: string;
}

export const strings: LocalizedStrings<LocaleStrings> = new LocalizedStringsFactory({
    en: enStrings,
    de: deStrings
});
`

**Comment by stefalda** [comment]
Hi @Larsrdev,
 sorry for the delay.

You're right but it would be a breaking change. 

In typescript types can be inferred by the instantiated value so there's no need to declare 

`export const strings: LocalizedStrings `

you can just say:

`export const strings = new LocalizedStrings(
`

Let me know if I'm missing anything.

Thanks

Stefano

**Comment by stefalda** [comment]
Check the suggested solution to work with Typescript:

[here](https://github.com/stefalda/react-localization/blob/master/README.md#typescript-support)

**Comment by Larsrdev** [comment]
Yea man, 
you are right. Thanks 👍 

The suggested solution needs some little change:

```
import LocalizedStrings, { LocalizedStringsMethods } from 'react-localization';

export interface LocaleStrings extends LocalizedStringsMethods {
    key1: string;
    key2: string;
}

export const strings: LocaleStrings = new LocalizedStrings({
    en: enStrings,
    de: deStrings
});
```

**Comment by qja0707** [comment]
You must post above example to main page. I wasted 2days to fix this problem
