### ISSUE TITLE
Add typescript definitions (d.ts)

### ISSUE THREAD

**Issue by aventurella** [stefalda/react-localization#7]
http://definitelytyped.org/guides/contributing.html

```typescript
declare module "react-localization" {
    interface LocalizedStringsMethods {
        setLanguage(language: string): void;
        getLanguage(): string;
        getInterfaceLanguage(): string;
        formatString(str: string, ...values: any[]): string
        getAvailableLanguages(): string[]
    }

    interface LocalizedStringsFactory {
        new (props: any): LocalizedStringsMethods;
    }

    var LocalizedStrings: LocalizedStringsFactory;
    export = LocalizedStrings;
}
```

**Comment by stefalda** [comment]
Hi @aventurella, I've added your definition file to the repository following this thread on [StackOverflow](http://stackoverflow.com/questions/37210059/how-to-add-a-typescript-definition-file-to-a-npm-package).

I've never done this before so I hope it works ok...

Stefano

**Comment by simopaasisalo** [comment]
@stefalda I can't seem to find the definitions from the DefinitelyTyped repository

**Comment by simopaasisalo** [comment]
Except.. npm install gives out the following error:
```
error TS2656: Exported external package typings file 'web/project/node_modules/react-localization/lib/LocalizedStrings.d.ts' is not a module. Please contact the package author to update the package definition.
```
So it seems that the typings file can't actually be a part of this repository, but it has to be an external file.

**Comment by aventurella** [comment]
I want to say you can include the typings in the repo:

http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Per those docs:

>There are two main ways you can publish your declaration files to npm:
>
> 1. bundling with your npm package, or
> 2. publishing to the @types organization on npm.

**Comment by simopaasisalo** [comment]
Ah, so it would seem.  In the current package.json the line is
` "typings": "./lib/LocalizedStrings.d.ts",`
Guessing `types` is the magic word

**Comment by simopaasisalo** [comment]
Ok, after setting the package.json to `types` and adding the location to my tsconfig, the npm install runs properly. I'll send a PR with the package.json fix

**Comment by aventurella** [comment]
I **think** that might be new as of TS 2.0 which just dropped this week? last week?

**Comment by stefalda** [comment]
Maybe... thank you for investigating the issue.

**Comment by simopaasisalo** [comment]
@stefalda Hi,
Could you also update the npm version to the newest one? It still has the old package.json, so there are still issues (at least for me) when npm install'ing from scratch.

**Comment by stefalda** [comment]
I've pushed it now...

Check it now...

**Comment by simopaasisalo** [comment]
@stefalda Still getting `typings`...weird

**Comment by stefalda** [comment]
Ouch... I've updated the Native repository... tonight I'll fix.. sorry

**Comment by stefalda** [comment]
Published... Let me know it it's OK...

**Comment by simopaasisalo** [comment]
Like a charm. Thanks!
