### ISSUE TITLE
Object doesn't support property or method 'assign' (IE 11)

### ISSUE THREAD

**Issue by NikunjPansuriya** [stefalda/react-localization#71]
i'm using latest version i.e. 1.0.5 and in IE 11 doesn't render.
![error](https://user-images.githubusercontent.com/20836849/38195507-68fbe342-369b-11e8-80f8-067034bf69d5.JPG)

**Comment by stefalda** [comment]
It's because Object.assign is not supported in IE.

At the end of [this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) there's a polyfill you can use.
